language: julia

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - hdf5-tools

julia:
  - 1.0
  - 1.5
  - nightly

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("FunctionalStateMachine")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

# matrix:
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false
